[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = true

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.default.optimizer_details.yulDetails]
optimizerSteps = "dhfoDgvulfnTUtnIf"
