[workspace]
members = [
  "programs/purge_game",
  "programs/purge_coin",
  "programs/purge_trophies",
]

[programs.localnet]
purge_game = "purGGamE1111111111111111111111111111111111111"
purge_coin = "purGCoin111111111111111111111111111111111111"
purge_trophies = "purGTroph111111111111111111111111111111111"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn anchor test"
